version: '3'

x-common:
  k3s: &k3s
    image: "rancher/k3s:v1.23.3-k3s1"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
    - 'registry-proxy'
    links:
    - 'registry-proxy:registry-proxy'
    privileged: true
    restart: always
  registry-proxy-env: &registry-proxy-env
    HTTP_PROXY: "registry-proxy:3128"
    HTTPS_PROXY: "registry-proxy:3128"
    NOPROXY_LIST: "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.local,.svc"
  registry-proxy-ca-vol: &registry-proxy-ca-vol |
    /tmp/istio-playground/registry-proxy-ca/ca.crt:/etc/ssl/certs/registry-proxy-ca.pem

services:
  server:
    <<: *k3s
    hostname: "server"
    command: ["server", "--disable", "traefik"]
    environment:
      <<: *registry-proxy-env
      K3S_TOKEN: &k3s-token very-secure-token
      K3S_KUBECONFIG_OUTPUT: /output/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: 666
    volumes:
    - *registry-proxy-ca-vol
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - ./tmp:/output
    ports:
    - 6443:6443 # API Server

  agent:
    <<: *k3s
    hostname: "agent"
    environment:
      <<: *registry-proxy-env
      K3S_URL: "https://server:6443"
      K3S_TOKEN: *k3s-token
    volumes:
    - *registry-proxy-ca-vol

  registry-proxy:
    image: "rpardini/docker-registry-proxy:0.6.4"
    volumes:
    - '/tmp/istio-playground/registry-proxy-ca:/ca'
    - '/tmp/istio-playground/registry-proxy-cache:/docker_mirror_cache'
    environment:
      ENABLE_MANIFEST_CACHE: "true"

  public-ca:
    image: "smallstep/step-ca:0.18.1"
    environment:
      DOCKER_STEPCA_INIT_NAME: "Istio Playground Public CA"
      DOCKER_STEPCA_INIT_DNS_NAMES: "localhost,public-ca,$$(hostname -f)"
    working_dir: /host
    volumes:
    - .:/host
    - ./tmp/public-ca:/home/step
    ports:
    - 9000:9000

  public-lb:
    image: nginx:1.21-alpine
    ports:
    - 8080:80
    - 8443:443
    volumes:
    - ./lib/nginx/00-default-cfg.sh:/docker-entrypoint.d/00-default-cfg.sh
    - ./lib/nginx/50-auto-reload.sh:/docker-entrypoint.d/50-auto-reload.sh
    - ./tmp/public-lb/nginx-conf.d:/etc/nginx/conf.d
    - .:/host

  tools:
    build:
      dockerfile: "Dockerfile.tools"
      context: "."
    network_mode: host
    tty: true
    environment:
      KUBECONFIG: /host/tmp/kubeconfig.yaml
    working_dir: /host
    volumes:
    - .:/host

volumes:
  k3s-server: {}
