version: '3'
x-common:
  cli: &cli
    working_dir: /host
    network_mode: host
    environment:
      KUBECONFIG: /host/kubeconfig.yaml
    volumes:
    - .:/host
  k8s-cli: &k8s-cli
    <<: *cli
    image: "alpine/k8s:1.20.7"


services:
  istioctl:
    <<: *cli
    image: "istio/istioctl:1.13.0-distroless"
    entrypoint: "istioctl"

  step-cli:
    <<: *cli
    image: "smallstep/step-cli:0.18.1"
    entrypoint: "step"

  kubectl:
    <<: *k8s-cli
    entrypoint: "kubectl"

  helm:
    <<: *k8s-cli
    entrypoint: "helm"
