---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: gateway
  version: 1.13.0
