apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: istio-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: base
  version: 1.13.0
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istiod
  namespace: istio-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: istiod
  version: 1.13.0
