#!/usr/bin/env bash

set -eu -o pipefail

source 00-common/shared.sh

START_TIME=`date "+%s"`

configure-cluster

echo "### Setup sample app"
kubectl apply -f 01-demo/sample-app.yaml
until kubectl wait --for=condition=available deployments --all -n demo; do sleep 1; done 2>/dev/null
istioctl analyze -n demo
echo

echo "### Test internal traffic routing"
POD="$(kubectl -n demo get pod -l app=ratings -ojsonpath='{.items[0].metadata.name}' 2>/dev/null)"
kubectl exec -n demo "${POD}" -c ratings -- curl -sSfLI productpage:9080/productpage
echo

echo "### Test external traffic routing"
echo "url: $(fetch-gateway-url)"
curl -sSfLI --connect-timeout 5 "$(fetch-gateway-url)/productpage"

END_TIME=`date "+%s"`

echo "### Setup time: $((${END_TIME} - ${START_TIME}))s"
