apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: minimal
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-ingress
      enabled: true
      label:
        istio: ingressgateway
    - name: istio-internalgateway
      namespace: istio-ingress
      enabled: true
      label:
        istio: internalgateway
      k8s:
        service:
          type: "ClusterIP"
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
