root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "${root}/aliases.sh"
source "${root}/ui.sh"
source "${root}/exec.sh"
source "${root}/tools.sh"
source "${root}/k8s.sh"
source "${root}/istio.sh"
source "${root}/ingress.sh"
source "${root}/bootstrap.sh"
source "${root}/apps.sh"
