#!/usr/bin/env bash

set -eu -o pipefail

ISTIOCTL='docker-compose run --rm istioctl'

START_TIME=`date "+%s"`

echo '### Setup k3s'
docker-compose up -d server agent
until kubectl wait --for=condition=ready node --all; do sleep 1; done 2>/dev/null
until kubectl wait --for=condition=available deployment/coredns -n kube-system; do sleep 1; done 2>/dev/null
until kubectl wait --for=condition=available deployment/metrics-server -n kube-system; do sleep 1; done 2>/dev/null
until kubectl wait --for=condition=available deployment/traefik -n kube-system; do sleep 1; done 2>/dev/null
echo

echo "### Setup Istio operator"
${ISTIOCTL} install --set profile=demo -y
kubectl label namespace default istio-injection=enabled --overwrite
${ISTIOCTL} analyze
echo

END_TIME=`date "+%s"`

echo "### Setup time: $((${END_TIME} - ${START_TIME}))s"
